### ISSUE TITLE
Ignoring personal interpretation bias, the datums(?) seem to have a bias

### ISSUE THREAD

**Issue by phsstory** [sdras/is-this-a-sandwich#5]
Assumptions and Observations
======
(Ingredient, Structure)

    1,1 | 2,1 | 3,1 | 10
    1,2 | 2,2 | 3,2 |  2
    1,3 | 2,3 | 3,3 |  7
    ----------------+
      7 |  2  |  10 | 

The count of each axis score in above table or if you prefer, the below table is the counts of each coordinate.

    2 | 1 | 7
    0 | 0 | 2
    5 | 1 | 1

* The player's score starts 0,0 (above and to the left of lawful good) 
* there appears to be a bias toward structure purism `(?,1)` and ingredient anarchy `(3,?)`. 
* There are no options to move toward Lawful Neutral `(1,2)` nor True Neutral `(2,2)`
* My chosen vocabulary to describe this situation is lacking.

Opinion
=====
* I believe there needs to be an equal number of `(?,3)`'s to `(?,1)`'s and the inverse.
* The players score should start in this coordinate system at `(2,2)`

**Comment by sdras** [comment]
Nah
